server:
  port: 80


eureka:
  instance:
    hostname: order80
  client:
    fetch-registry: false #表示自己非服务中心
    register-with-eureka: true #表示向服务中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
spring:
  application:
    name: cloud-consumer-order80
